// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_group.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserGroup _$UserGroupFromJson(Map<String, dynamic> json) => UserGroup(
      id: json['id'] as String?,
      name: json['name'] as String?,
      subDomain: json['subDomain'] as String?,
      timeZone: json['timeZone'] as String?,
      primaryContactName: json['primaryContactName'] as String?,
      primaryContactMobile: json['primaryContactMobile'] as String?,
      primaryContactEmail: json['primaryContactEmail'] as String?,
      primaryContactWebsite: json['primaryContactWebsite'] as String?,
      address1: json['address1'] as String?,
      address2: json['address2'] as String?,
      country: json['country'] as String?,
      state: json['state'] as String?,
      city: json['city'] as String?,
      zipCode: json['zipCode'] as String?,
      language: json['language'] as String?,
      isShowLangOpt: json['isShowLangOpt'] as String?,
      otherLaguageChine: json['otherLaguageChine'] as String?,
      otherLaguageEnglish: json['otherLaguageEnglish'] as String?,
      otherLaguageUSA: json['otherLaguageUSA'] as String?,
      otherLaguageFrench: json['otherLaguageFrench'] as String?,
      creditCardName: json['creditCardName'] as String?,
      creditCardNumber: json['creditCardNumber'] as String?,
      creditCardExp: json['creditCardExp'] as String?,
      creditCardCVC: json['creditCardCVC'] as String?,
      isEnableUserRegistration: json['isEnableUserRegistration'] as String?,
      loginHyperColor: json['loginHyperColor'] as String?,
      loginHyperHover: json['loginHyperHover'] as String?,
      loginLogo: json['loginLogo'] as String?,
      loginImage: json['loginImage'] as String?,
      colorToolbarIcon: json['colorToolbarIcon'] as String?,
      colorToolbarIconHover: json['colorToolbarIconHover'] as String?,
      colorToolbarHyperLink: json['colorToolbarHyperLink'] as String?,
      colorToolbarHyperLinkHover: json['colorToolbarHyperLinkHover'] as String?,
      colorToolbarBackground: json['colorToolbarBackground'] as String?,
      colorToolbarSearchText: json['colorToolbarSearchText'] as String?,
      colorToolbarSearchBorder: json['colorToolbarSearchBorder'] as String?,
      colorToolbarLogo: json['colorToolbarLogo'] as String?,
      colorBodyButton: json['colorBodyButton'] as String?,
      colorBodyButtonHover: json['colorBodyButtonHover'] as String?,
      colorBodyButtonText: json['colorBodyButtonText'] as String?,
      colorBodyButtonTextHover: json['colorBodyButtonTextHover'] as String?,
      colorBodyImage: json['colorBodyImage'] as String?,
      adminPrising: json['adminPrising'] as String?,
      subUserGroupLanuage: json['subUserGroupLanuage'] as String?,
      subUserGroupBranding: json['subUserGroupBranding'] as String?,
      subUserGroupBilling: json['subUserGroupBilling'] as String?,
      acn: json['acn'] as String?,
    );

Map<String, dynamic> _$UserGroupToJson(UserGroup instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'subDomain': instance.subDomain,
      'timeZone': instance.timeZone,
      'primaryContactName': instance.primaryContactName,
      'primaryContactMobile': instance.primaryContactMobile,
      'primaryContactEmail': instance.primaryContactEmail,
      'primaryContactWebsite': instance.primaryContactWebsite,
      'address1': instance.address1,
      'address2': instance.address2,
      'country': instance.country,
      'state': instance.state,
      'city': instance.city,
      'zipCode': instance.zipCode,
      'language': instance.language,
      'isShowLangOpt': instance.isShowLangOpt,
      'otherLaguageChine': instance.otherLaguageChine,
      'otherLaguageEnglish': instance.otherLaguageEnglish,
      'otherLaguageUSA': instance.otherLaguageUSA,
      'otherLaguageFrench': instance.otherLaguageFrench,
      'creditCardName': instance.creditCardName,
      'creditCardNumber': instance.creditCardNumber,
      'creditCardExp': instance.creditCardExp,
      'creditCardCVC': instance.creditCardCVC,
      'isEnableUserRegistration': instance.isEnableUserRegistration,
      'loginHyperColor': instance.loginHyperColor,
      'loginHyperHover': instance.loginHyperHover,
      'loginLogo': instance.loginLogo,
      'loginImage': instance.loginImage,
      'colorToolbarIcon': instance.colorToolbarIcon,
      'colorToolbarIconHover': instance.colorToolbarIconHover,
      'colorToolbarHyperLink': instance.colorToolbarHyperLink,
      'colorToolbarHyperLinkHover': instance.colorToolbarHyperLinkHover,
      'colorToolbarBackground': instance.colorToolbarBackground,
      'colorToolbarSearchText': instance.colorToolbarSearchText,
      'colorToolbarSearchBorder': instance.colorToolbarSearchBorder,
      'colorToolbarLogo': instance.colorToolbarLogo,
      'colorBodyButton': instance.colorBodyButton,
      'colorBodyButtonHover': instance.colorBodyButtonHover,
      'colorBodyButtonText': instance.colorBodyButtonText,
      'colorBodyButtonTextHover': instance.colorBodyButtonTextHover,
      'colorBodyImage': instance.colorBodyImage,
      'adminPrising': instance.adminPrising,
      'subUserGroupLanuage': instance.subUserGroupLanuage,
      'subUserGroupBranding': instance.subUserGroupBranding,
      'subUserGroupBilling': instance.subUserGroupBilling,
      'acn': instance.acn,
    };
