// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_groups.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserGroups _$UserGroupsFromJson(Map<String, dynamic> json) => UserGroups(
      id: json['id'] as String?,
      name: json['name'] as String?,
      subDomain: json['sub_domain'] as String?,
      timeZone: json['time_zone'] as String?,
      primaryContactName: json['primary_contact_name'] as String?,
      primaryContactMobile: json['primary_contact_mobile'] as String?,
      primaryContactEmail: json['primary_contact_email'] as String?,
      primaryContactWebsite: json['primary_contact_website'] as String?,
      address1: json['address1'] as String?,
      address2: json['address2'] as String?,
      country: json['country'] as String?,
      state: json['state'] as String?,
      city: json['city'] as String?,
      zipCode: json['zip_code'] as String?,
      defaultLanguage: json['default_language'] as String?,
      isShowLanguageOption: json['is_show_language_option'] as bool?,
      laguageChineseSimplified: json['laguage_chinese_simplified'] as bool?,
      laguageEnglishAUS: json['laguage_english_a_u_s'] as bool?,
      laguageEnglishUSA: json['laguage_english_u_s_a'] as bool?,
      laguageFrench: json['laguage_french'] as bool?,
      creditCardName: json['credit_card_name'] as String?,
      creditCardNumber: json['credit_card_number'] as String?,
      creditCardExp: json['credit_card_exp'] as String?,
      creditCardCVC: json['credit_card_c_v_c'] as String?,
      isEnableUserRegistration: json['is_enable_user_registration'] as String?,
      loginHyperColor: json['login_hyper_color'] as String?,
      loginHyperHover: json['login_hyper_hover'] as String?,
      loginLogo: json['login_logo'] as String?,
      loginImage: json['login_image'] as String?,
      colorToolbarIcon: json['color_toolbar_icon'] as String?,
      colorToolbarIconHover: json['color_toolbar_icon_hover'] as String?,
      colorToolbarHyperLink: json['color_toolbar_hyper_link'] as String?,
      colorToolbarHyperLinkHover:
          json['color_toolbar_hyper_link_hover'] as String?,
      colorToolbarBackground: json['color_toolbar_background'] as String?,
      colorToolbarSearchText: json['color_toolbar_search_text'] as String?,
      colorToolbarSearchBorder: json['color_toolbar_search_border'] as String?,
      colorToolbarLogo: json['color_toolbar_logo'] as String?,
      colorBodyButton: json['color_body_button'] as String?,
      colorBodyButtonHover: json['color_body_button_hover'] as String?,
      colorBodyButtonText: json['color_body_button_text'] as String?,
      colorBodyButtonTextHover: json['color_body_button_text_hover'] as String?,
      colorBodyImage: json['color_body_image'] as String?,
      adminPrising:
          $enumDecodeNullable(_$AdminPricingEnumMap, json['admin_prising']) ??
              AdminPricing.Individual,
      subUserGroupLanguge: json['sub_user_group_languge'] as String?,
      subUserGroupBranding: json['sub_user_group_branding'] as String?,
      subUserGroupBilling: json['sub_user_group_billing'] as String?,
      acn: json['acn'] as String?,
    );

Map<String, dynamic> _$UserGroupsToJson(UserGroups instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'sub_domain': instance.subDomain,
      'time_zone': instance.timeZone,
      'primary_contact_name': instance.primaryContactName,
      'primary_contact_mobile': instance.primaryContactMobile,
      'primary_contact_email': instance.primaryContactEmail,
      'primary_contact_website': instance.primaryContactWebsite,
      'address1': instance.address1,
      'address2': instance.address2,
      'country': instance.country,
      'state': instance.state,
      'city': instance.city,
      'zip_code': instance.zipCode,
      'default_language': instance.defaultLanguage,
      'is_show_language_option': instance.isShowLanguageOption,
      'laguage_chinese_simplified': instance.laguageChineseSimplified,
      'laguage_english_a_u_s': instance.laguageEnglishAUS,
      'laguage_english_u_s_a': instance.laguageEnglishUSA,
      'laguage_french': instance.laguageFrench,
      'credit_card_name': instance.creditCardName,
      'credit_card_number': instance.creditCardNumber,
      'credit_card_exp': instance.creditCardExp,
      'credit_card_c_v_c': instance.creditCardCVC,
      'is_enable_user_registration': instance.isEnableUserRegistration,
      'login_hyper_color': instance.loginHyperColor,
      'login_hyper_hover': instance.loginHyperHover,
      'login_logo': instance.loginLogo,
      'login_image': instance.loginImage,
      'color_toolbar_icon': instance.colorToolbarIcon,
      'color_toolbar_icon_hover': instance.colorToolbarIconHover,
      'color_toolbar_hyper_link': instance.colorToolbarHyperLink,
      'color_toolbar_hyper_link_hover': instance.colorToolbarHyperLinkHover,
      'color_toolbar_background': instance.colorToolbarBackground,
      'color_toolbar_search_text': instance.colorToolbarSearchText,
      'color_toolbar_search_border': instance.colorToolbarSearchBorder,
      'color_toolbar_logo': instance.colorToolbarLogo,
      'color_body_button': instance.colorBodyButton,
      'color_body_button_hover': instance.colorBodyButtonHover,
      'color_body_button_text': instance.colorBodyButtonText,
      'color_body_button_text_hover': instance.colorBodyButtonTextHover,
      'color_body_image': instance.colorBodyImage,
      'admin_prising': _$AdminPricingEnumMap[instance.adminPrising],
      'sub_user_group_languge': instance.subUserGroupLanguge,
      'sub_user_group_branding': instance.subUserGroupBranding,
      'sub_user_group_billing': instance.subUserGroupBilling,
      'acn': instance.acn,
    };

const _$AdminPricingEnumMap = {
  AdminPricing.Individual: 'Individual',
  AdminPricing.Business: 'Business',
  AdminPricing.BusinessPlus: 'BusinessPlus',
  AdminPricing.Enterprise: 'Enterprise',
  AdminPricing.EnterprisePlus: 'EnterprisePlus',
};
